### ISSUE TITLE
关于yolov5_nano_p6

### ISSUE THREAD

**Issue by gaoxumustwin** [cqu20160901/yolov5p6_caffe_onnx_tensorRT_rknn#3]
大佬您好，请问您这个yolov5_nano_p6是您对yolov5进行修改给出的名称吗？ 还是yolov5的修改别 可以给一个yolov5_nano_p6的仓库地址吗？

**Comment by Tiankong-1** [comment]
https://github.com/ultralytics/yolov5/releases/tag/v6.0

**Comment by gaoxumustwin** [comment]
> https://github.com/ultralytics/yolov5/releases/tag/v6.0

Thank you very much for your reply
